url_type:
    image:
        - png
        - svg
        - jpg
        - jpeg
        - gif
    resource:
        - js
        - css
        - pdf
        - doc
        - docx

headers:
    User-Agent:
        www: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'
        mobile: 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1'

default_timeout: 20